name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore TestAndSurvey.sln

    - name: Build solution
      run: dotnet build TestAndSurvey.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test TestAndSurvey.sln --no-build --configuration Release --verbosity normal
