name: .NET Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore backend/TestAndSurvey/TestAndSurvey.sln

    - name: Build
      run: dotnet build backend/TestAndSurvey/TestAndSurvey.sln --no-restore

    - name: Run tests
      run: dotnet test backend/TestAndSurvey/TestAndSurvey.sln --no-build --verbosity normal
